module.exports = (req, res, next) => {
    if (req.url === '/token') {
        if (req.body.otpValue) {
            return res.send({
                access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWV3TWFwcGluZ3MiOnt9LCJ2aWV3TmFtZSI6InJlZGlyZWN0Oi9wL2hvbWUuZG8iLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaG9tZVBob25lIjpudWxsLCJuYW1lIjpudWxsLCJleHAiOjE1Njg2Mzc2OTEsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6ImJmMGZjZGE2LTM0NjUtNDc1ZS1hNDkwLWExMGY3N2ZkYjhhYiIsImVtYWlsIjpudWxsLCJjbGllbnRfaWQiOiJjbGllbnRJZCIsInVzZXJuYW1lIjoiWlI1NTU3MTkifQ.S5tDZQK_4eq9f5kqbg2J1IoI0p8uaqHssrQDZy8aGfc",
                expires_in: 3600,
                refresh_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2aWV3TWFwcGluZ3MiOnt9LCJ2aWV3TmFtZSI6InJlZGlyZWN0Oi9wL2hvbWUuZG8iLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXSwiaG9tZVBob25lIjpudWxsLCJhdGkiOiJiZjBmY2RhNi0zNDY1LTQ3NWUtYTQ5MC1hMTBmNzdmZGI4YWIiLCJuYW1lIjpudWxsLCJleHAiOjE1Njg2Mzc5NzEsImF1dGhvcml0aWVzIjpbIkFETUlOIl0sImp0aSI6ImE4NjZlMTMxLTdiYTItNDc5NC1iNDM5LTgwMTdiMjJkZTAxNSIsImVtYWlsIjpudWxsLCJjbGllbnRfaWQiOiJjbGllbnRJZCIsInVzZXJuYW1lIjoiWlI1NTU3MTkifQ.HBPTrsDgkoQK7fX-fTG8rDvVVrq2QMWDrTrfpIFeIVI",
                scope: "read write",
                token_type: "bearer"
            });
        } else {
            return res.send({
                "authenticationType": "OTP_SMS",
                "expires_in": 3600,
                "otpExpiration": 3600,
                "otpSize": 4,
                "pre_auth_token": "40564a89-69b5-4d53-8167-711f8de734f3"
            });
        }
    }

    if (req.path == '/pay') {
        return res.send(billPayment);
    }

    if (req.path == '/fields') {
        return res.send(fields);
    }

    if (req.path == '/oneTimePayment') {
        return res.send(oneTimePayment);
    }
    console.log(req.path);
    next();
}

const oneTimePayment = {
    "billPage": {
        "items": [
            {
                "isPagableByCard": true,
                "billDetails": "400001297408400001297342",
                "billAmountDue": "302.29",
                "biller": "010 - Riyadh Municipality",
                "billStatus": "Unpaid",
                "billBillingDate": "",
                "billDueDate": "20 Dec 12",
                "billNumber": "400001297408",
                "index": "0",
                "billAmountDueFmt": "302.29 SAR",
                "billOtherInformation": "                                                                                ",
                "value": null,
                "billAssociated": null,
                "billAccount": "400001297342",
                "billAmountDueIsDB": true,
                "alias": "Sam Municipal 02",
                "lblAddDescription": "Add nickname",
                "exact": true,
                "lblSaudiRiyal": null,
                "billerNumber": "010",
                "dact": false,
                "associated": true,
                "associatedAlias": null,
                "modified": false,
                "billShowDueDate": "Due 20 Dec 12",
                "lblMoreInfo": "More info",
                "lblNoDescription": "No nickname"
            }
        ],
        "offset": 0,
        "size": 1,
        "total": 2,
        "paid": "3.02 SAR",
        "biller": null,
        "account": null,
        "billingDtt": null,
        "dueDtt": null,
        "accountsList": null,
        "other": null,
        "paidCurrency": "SAR",
        "paidFmt": null,
        "maxBillsTransaction": 8
    },
    "isPagableByCard": true
};

const fields = [
    {
        "text": null,
        "value": null,
        "validation": "minlength=   maxlength=  ",
        "label": "Account Number",
        "type": "input",
        "items": null,
        "id": "inMOI1",
        "minLength": "  ",
        "maxLength": "  ",
        "self": null,
        "validationClass": null,
        "disable": true,
        "required": false
    },
    {
        "text": null,
        "value": "12313206848",
        "validation": "minlength=   maxlength=  ",
        "label": "Service Line Number",
        "type": "input",
        "items": null,
        "id": "inMOI2",
        "minLength": "  ",
        "maxLength": "  ",
        "self": null,
        "validationClass": null,
        "disable": true,
        "required": false
    }
]

const bills = [
    {
        "isPagableByCard": true,
        "billDetails": "002123328002123328",
        "billAmountDue": "500",
        "biller": "002 - Saudi Electricity Company",
        "billStatus": "Paid",
        "billBillingDate": "31 May 18",
        "billDueDate": "15 Jul 19",
        "billNumber": "002123328",
        "index": "0",
        "billAmountDueFmt": "-500.00 SAR",
        "billOtherInformation": "                                                                                ",
        "value": null,
        "billAssociated": null,
        "billAccount": "002123328",
        "billAmountDueIsDB": true,
        "alias": "123",
        "lblAddDescription": "Add nickname",
        "exact": false,
        "lblSaudiRiyal": null,
        "billerNumber": "002",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                00188831972",
        "billAmountDue": "159",
        "biller": "001 - STC",
        "billStatus": "Paid",
        "billBillingDate": "31 Oct 18",
        "billDueDate": "15 Jul 19",
        "billNumber": "                                ",
        "index": "1",
        "billAmountDueFmt": "0.00 SAR",
        "billOtherInformation": "                                                                                ",
        "value": null,
        "billAssociated": null,
        "billAccount": "00188831972",
        "billAmountDueIsDB": false,
        "alias": "STC 02",
        "lblAddDescription": "Add nickname",
        "exact": true,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": true,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                00133331992",
        "billAmountDue": "2.55",
        "biller": "001 - STC",
        "billStatus": "Paid",
        "billBillingDate": "31 Oct 18",
        "billDueDate": "15 Jul 19",
        "billNumber": "                                ",
        "index": "2",
        "billAmountDueFmt": "2.55 SAR",
        "billOtherInformation": "                                                                                ",
        "value": null,
        "billAssociated": null,
        "billAccount": "00133331992",
        "billAmountDueIsDB": false,
        "alias": "STC 03",
        "lblAddDescription": "Add nickname",
        "exact": true,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                00133331994",
        "billAmountDue": "323.56",
        "biller": "001 - STC",
        "billStatus": "Paid",
        "billBillingDate": "31 Oct 18",
        "billDueDate": "15 Jul 19",
        "billNumber": "                                ",
        "index": "3",
        "billAmountDueFmt": "323.56 SAR",
        "billOtherInformation": "                                                                                ",
        "value": null,
        "billAssociated": null,
        "billAccount": "00133331994",
        "billAmountDueIsDB": false,
        "alias": "myphonebill2",
        "lblAddDescription": "Add nickname",
        "exact": true,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                35000043794",
        "billAmountDue": "0",
        "biller": "001 - STC",
        "billStatus": "Unpaid",
        "billBillingDate": "23 Nov 16",
        "billDueDate": "23 Dec 16",
        "billNumber": "                                ",
        "index": "4",
        "billAmountDueFmt": "0.00 SAR",
        "billOtherInformation": "BTIQbRzvSPHQA6z/3NeQyA==",
        "value": null,
        "billAssociated": null,
        "billAccount": "35000043794",
        "billAmountDueIsDB": false,
        "alias": "STC 07",
        "lblAddDescription": "Add nickname",
        "exact": false,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": "Due 23 Dec 16",
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                35000043794",
        "billAmountDue": "0",
        "biller": "001 - STC",
        "billStatus": "Paid",
        "billBillingDate": "",
        "billDueDate": "21 Dec 16",
        "billNumber": "                                ",
        "index": "5",
        "billAmountDueFmt": "0.00 SAR",
        "billOtherInformation": "BTIQbRzvSPHQA6z/3NeQyA==",
        "value": null,
        "billAssociated": null,
        "billAccount": "35000043794",
        "billAmountDueIsDB": false,
        "alias": "STC 07",
        "lblAddDescription": "Add nickname",
        "exact": true,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                05223696805",
        "billAmountDue": "0",
        "biller": "001 - STC",
        "billStatus": "Paid",
        "billBillingDate": "",
        "billDueDate": "15 Jul 16",
        "billNumber": "                                ",
        "index": "6",
        "billAmountDueFmt": "0.00 SAR",
        "billOtherInformation": "BTIQbRzvSPHQA6z/3NeQyA==",
        "value": null,
        "billAssociated": null,
        "billAccount": "05223696805",
        "billAmountDueIsDB": false,
        "alias": "STC 05",
        "lblAddDescription": "Add nickname",
        "exact": true,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    },
    {
        "isPagableByCard": true,
        "billDetails": "                                05836666405",
        "billAmountDue": "0",
        "biller": "001 - STC",
        "billStatus": "Paid",
        "billBillingDate": "",
        "billDueDate": "15 Jul 16",
        "billNumber": "                                ",
        "index": "7",
        "billAmountDueFmt": "0.00 SAR",
        "billOtherInformation": "BTIQbRzvSPHQA6z/3NeQyA==",
        "value": null,
        "billAssociated": null,
        "billAccount": "05836666405",
        "billAmountDueIsDB": false,
        "alias": "STC 06",
        "lblAddDescription": "Add nickname",
        "exact": true,
        "lblSaudiRiyal": null,
        "billerNumber": "001",
        "dact": false,
        "associated": true,
        "associatedAlias": null,
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": "More info",
        "lblNoDescription": "No nickname"
    }
];

const billPayment = {
    "bills": [{
        "isPagableByCard": null,
        "billDetails": "05514444413",
        "billAmountDue": "1.00",
        "biller": "001 - STC",
        "billStatus": "Part",
        "billBillingDate": "05 ago 07",
        "billDueDate": "05 ago 07",
        "billNumber": "                                ",
        "index": "2",
        "billAmountDueFmt": "1.00 SAR",
        "billOtherInformation": "billOtherInformation",
        "value": null,
        "billAssociated": null,
        "billAccount": null,
        "billAmountDueIsDB": false,
        "alias": null,
        "lblAddDescription": null,
        "exact": false,
        "lblSaudiRiyal": null,
        "billerNumber": null,
        "dact": false,
        "associated": true,
        "associatedAlias": "Yes",
        "modified": false,
        "billShowDueDate": null,
        "lblMoreInfo": null,
        "lblNoDescription": null
    }],
    "debitAccountMask": null,
    "balanceAccount": null,
    "paymentReference": "BIL00001",
    "totalNumberOfBills": "1",
    "groupReferenceNumber": "537457",
    "paymentDate": "18 dic 14 15:27",
    "paymentAmount": "1.00 SAR",
    "debitAmount": "1.00 SAR",
    "debitAccount": null,
    "paymentMethod": "creditCards",
    "creditCard": "00155530 VISA Platinum"
}